//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePIF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompactAddressFormat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompactAddressFormat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePIF.Properties.CompactAddressFormat", typeof(CompactAddressFormat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ad {
            get {
                return ResourceManager.GetString("Country_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ae {
            get {
                return ResourceManager.GetString("Country_ae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_af {
            get {
                return ResourceManager.GetString("Country_af", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ag {
            get {
                return ResourceManager.GetString("Country_ag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_ai {
            get {
                return ResourceManager.GetString("Country_ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_al {
            get {
                return ResourceManager.GetString("Country_al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_am {
            get {
                return ResourceManager.GetString("Country_am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ao {
            get {
                return ResourceManager.GetString("Country_ao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_ar {
            get {
                return ResourceManager.GetString("Country_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_as {
            get {
                return ResourceManager.GetString("Country_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_at {
            get {
                return ResourceManager.GetString("Country_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_au {
            get {
                return ResourceManager.GetString("Country_au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_aw {
            get {
                return ResourceManager.GetString("Country_aw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_az {
            get {
                return ResourceManager.GetString("Country_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ba {
            get {
                return ResourceManager.GetString("Country_ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bb {
            get {
                return ResourceManager.GetString("Country_bb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_bd {
            get {
                return ResourceManager.GetString("Country_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_be {
            get {
                return ResourceManager.GetString("Country_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_bf {
            get {
                return ResourceManager.GetString("Country_bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_bg {
            get {
                return ResourceManager.GetString("Country_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_bh {
            get {
                return ResourceManager.GetString("Country_bh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bi {
            get {
                return ResourceManager.GetString("Country_bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bj {
            get {
                return ResourceManager.GetString("Country_bj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_bl {
            get {
                return ResourceManager.GetString("Country_bl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_bm {
            get {
                return ResourceManager.GetString("Country_bm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_bn {
            get {
                return ResourceManager.GetString("Country_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bo {
            get {
                return ResourceManager.GetString("Country_bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_br {
            get {
                return ResourceManager.GetString("Country_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_bs {
            get {
                return ResourceManager.GetString("Country_bs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bt {
            get {
                return ResourceManager.GetString("Country_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_bw {
            get {
                return ResourceManager.GetString("Country_bw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_by {
            get {
                return ResourceManager.GetString("Country_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_bz {
            get {
                return ResourceManager.GetString("Country_bz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_ca {
            get {
                return ResourceManager.GetString("Country_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_cc {
            get {
                return ResourceManager.GetString("Country_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_cd {
            get {
                return ResourceManager.GetString("Country_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_cf {
            get {
                return ResourceManager.GetString("Country_cf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_cg {
            get {
                return ResourceManager.GetString("Country_cg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ch {
            get {
                return ResourceManager.GetString("Country_ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ci {
            get {
                return ResourceManager.GetString("Country_ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ck {
            get {
                return ResourceManager.GetString("Country_ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cl {
            get {
                return ResourceManager.GetString("Country_cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_cm {
            get {
                return ResourceManager.GetString("Country_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_cn {
            get {
                return ResourceManager.GetString("Country_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_co {
            get {
                return ResourceManager.GetString("Country_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cr {
            get {
                return ResourceManager.GetString("Country_cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cu {
            get {
                return ResourceManager.GetString("Country_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cv {
            get {
                return ResourceManager.GetString("Country_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_cw {
            get {
                return ResourceManager.GetString("Country_cw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_cx {
            get {
                return ResourceManager.GetString("Country_cx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cy {
            get {
                return ResourceManager.GetString("Country_cy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_cz {
            get {
                return ResourceManager.GetString("Country_cz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_de {
            get {
                return ResourceManager.GetString("Country_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_dj {
            get {
                return ResourceManager.GetString("Country_dj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_dk {
            get {
                return ResourceManager.GetString("Country_dk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_dm {
            get {
                return ResourceManager.GetString("Country_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|zip|city|country.
        /// </summary>
        internal static string Country_do {
            get {
                return ResourceManager.GetString("Country_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_dz {
            get {
                return ResourceManager.GetString("Country_dz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ec {
            get {
                return ResourceManager.GetString("Country_ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ee {
            get {
                return ResourceManager.GetString("Country_ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|country.
        /// </summary>
        internal static string Country_eg {
            get {
                return ResourceManager.GetString("Country_eg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_eh {
            get {
                return ResourceManager.GetString("Country_eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_er {
            get {
                return ResourceManager.GetString("Country_er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_es {
            get {
                return ResourceManager.GetString("Country_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_es_cn {
            get {
                return ResourceManager.GetString("Country_es_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_et {
            get {
                return ResourceManager.GetString("Country_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_fi {
            get {
                return ResourceManager.GetString("Country_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|country.
        /// </summary>
        internal static string Country_fj {
            get {
                return ResourceManager.GetString("Country_fj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_fk {
            get {
                return ResourceManager.GetString("Country_fk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_fm {
            get {
                return ResourceManager.GetString("Country_fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_fo {
            get {
                return ResourceManager.GetString("Country_fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_fr {
            get {
                return ResourceManager.GetString("Country_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ga {
            get {
                return ResourceManager.GetString("Country_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_gb {
            get {
                return ResourceManager.GetString("Country_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gd {
            get {
                return ResourceManager.GetString("Country_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ge {
            get {
                return ResourceManager.GetString("Country_ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gf {
            get {
                return ResourceManager.GetString("Country_gf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gh {
            get {
                return ResourceManager.GetString("Country_gh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gi {
            get {
                return ResourceManager.GetString("Country_gi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gl {
            get {
                return ResourceManager.GetString("Country_gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gm {
            get {
                return ResourceManager.GetString("Country_gm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gn {
            get {
                return ResourceManager.GetString("Country_gn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gp {
            get {
                return ResourceManager.GetString("Country_gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gq {
            get {
                return ResourceManager.GetString("Country_gq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gr {
            get {
                return ResourceManager.GetString("Country_gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_gs {
            get {
                return ResourceManager.GetString("Country_gs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gt {
            get {
                return ResourceManager.GetString("Country_gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_gu {
            get {
                return ResourceManager.GetString("Country_gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_gw {
            get {
                return ResourceManager.GetString("Country_gw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_gy {
            get {
                return ResourceManager.GetString("Country_gy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_hk {
            get {
                return ResourceManager.GetString("Country_hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_hn {
            get {
                return ResourceManager.GetString("Country_hn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_hr {
            get {
                return ResourceManager.GetString("Country_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ht {
            get {
                return ResourceManager.GetString("Country_ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip|city|street|country.
        /// </summary>
        internal static string Country_hu {
            get {
                return ResourceManager.GetString("Country_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_id {
            get {
                return ResourceManager.GetString("Country_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_ie {
            get {
                return ResourceManager.GetString("Country_ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_il {
            get {
                return ResourceManager.GetString("Country_il", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_im {
            get {
                return ResourceManager.GetString("Country_im", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city zip|country.
        /// </summary>
        internal static string Country_in {
            get {
                return ResourceManager.GetString("Country_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_iq {
            get {
                return ResourceManager.GetString("Country_iq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ir {
            get {
                return ResourceManager.GetString("Country_ir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_is {
            get {
                return ResourceManager.GetString("Country_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_it {
            get {
                return ResourceManager.GetString("Country_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_je {
            get {
                return ResourceManager.GetString("Country_je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_jm {
            get {
                return ResourceManager.GetString("Country_jm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region|state|street|city|zip|country.
        /// </summary>
        internal static string Country_jo {
            get {
                return ResourceManager.GetString("Country_jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip|state|city|street|country.
        /// </summary>
        internal static string Country_jp {
            get {
                return ResourceManager.GetString("Country_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_ke {
            get {
                return ResourceManager.GetString("Country_ke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip|city|street|country.
        /// </summary>
        internal static string Country_kg {
            get {
                return ResourceManager.GetString("Country_kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_kh {
            get {
                return ResourceManager.GetString("Country_kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_ki {
            get {
                return ResourceManager.GetString("Country_ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_km {
            get {
                return ResourceManager.GetString("Country_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_kn {
            get {
                return ResourceManager.GetString("Country_kn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_kp {
            get {
                return ResourceManager.GetString("Country_kp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_kr {
            get {
                return ResourceManager.GetString("Country_kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_kw {
            get {
                return ResourceManager.GetString("Country_kw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|country.
        /// </summary>
        internal static string Country_ky {
            get {
                return ResourceManager.GetString("Country_ky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|region|zip|country.
        /// </summary>
        internal static string Country_kz {
            get {
                return ResourceManager.GetString("Country_kz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_la {
            get {
                return ResourceManager.GetString("Country_la", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_lb {
            get {
                return ResourceManager.GetString("Country_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_lc {
            get {
                return ResourceManager.GetString("Country_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_li {
            get {
                return ResourceManager.GetString("Country_li", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_lk {
            get {
                return ResourceManager.GetString("Country_lk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_lr {
            get {
                return ResourceManager.GetString("Country_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_ls {
            get {
                return ResourceManager.GetString("Country_ls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_lt {
            get {
                return ResourceManager.GetString("Country_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_lu {
            get {
                return ResourceManager.GetString("Country_lu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_lv {
            get {
                return ResourceManager.GetString("Country_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ly {
            get {
                return ResourceManager.GetString("Country_ly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ma {
            get {
                return ResourceManager.GetString("Country_ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mc {
            get {
                return ResourceManager.GetString("Country_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_md {
            get {
                return ResourceManager.GetString("Country_md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_me {
            get {
                return ResourceManager.GetString("Country_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mf {
            get {
                return ResourceManager.GetString("Country_mf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mg {
            get {
                return ResourceManager.GetString("Country_mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mh {
            get {
                return ResourceManager.GetString("Country_mh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mk {
            get {
                return ResourceManager.GetString("Country_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ml {
            get {
                return ResourceManager.GetString("Country_ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_mm {
            get {
                return ResourceManager.GetString("Country_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_mn {
            get {
                return ResourceManager.GetString("Country_mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_mo {
            get {
                return ResourceManager.GetString("Country_mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mq {
            get {
                return ResourceManager.GetString("Country_mq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_mr {
            get {
                return ResourceManager.GetString("Country_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ms {
            get {
                return ResourceManager.GetString("Country_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_mt {
            get {
                return ResourceManager.GetString("Country_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_mu {
            get {
                return ResourceManager.GetString("Country_mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_mv {
            get {
                return ResourceManager.GetString("Country_mv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_mw {
            get {
                return ResourceManager.GetString("Country_mw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_mx {
            get {
                return ResourceManager.GetString("Country_mx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_my {
            get {
                return ResourceManager.GetString("Country_my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_mz {
            get {
                return ResourceManager.GetString("Country_mz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_na {
            get {
                return ResourceManager.GetString("Country_na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_nc {
            get {
                return ResourceManager.GetString("Country_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ne {
            get {
                return ResourceManager.GetString("Country_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_nf {
            get {
                return ResourceManager.GetString("Country_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|state|country.
        /// </summary>
        internal static string Country_ng {
            get {
                return ResourceManager.GetString("Country_ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_ni {
            get {
                return ResourceManager.GetString("Country_ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_nl {
            get {
                return ResourceManager.GetString("Country_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_no {
            get {
                return ResourceManager.GetString("Country_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_np {
            get {
                return ResourceManager.GetString("Country_np", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_nr {
            get {
                return ResourceManager.GetString("Country_nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_nu {
            get {
                return ResourceManager.GetString("Country_nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|zip|country.
        /// </summary>
        internal static string Country_nz {
            get {
                return ResourceManager.GetString("Country_nz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_om {
            get {
                return ResourceManager.GetString("Country_om", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_pa {
            get {
                return ResourceManager.GetString("Country_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_pe {
            get {
                return ResourceManager.GetString("Country_pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_pf {
            get {
                return ResourceManager.GetString("Country_pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|state|country.
        /// </summary>
        internal static string Country_pg {
            get {
                return ResourceManager.GetString("Country_pg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|zip|city|country.
        /// </summary>
        internal static string Country_ph {
            get {
                return ResourceManager.GetString("Country_ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_pk {
            get {
                return ResourceManager.GetString("Country_pk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_pl {
            get {
                return ResourceManager.GetString("Country_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_pn {
            get {
                return ResourceManager.GetString("Country_pn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_pr {
            get {
                return ResourceManager.GetString("Country_pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ps {
            get {
                return ResourceManager.GetString("Country_ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_pt {
            get {
                return ResourceManager.GetString("Country_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_pw {
            get {
                return ResourceManager.GetString("Country_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_py {
            get {
                return ResourceManager.GetString("Country_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_qa {
            get {
                return ResourceManager.GetString("Country_qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_re {
            get {
                return ResourceManager.GetString("Country_re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ro {
            get {
                return ResourceManager.GetString("Country_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_rs {
            get {
                return ResourceManager.GetString("Country_rs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country|zip.
        /// </summary>
        internal static string Country_ru {
            get {
                return ResourceManager.GetString("Country_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_rw {
            get {
                return ResourceManager.GetString("Country_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_sa {
            get {
                return ResourceManager.GetString("Country_sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_sb {
            get {
                return ResourceManager.GetString("Country_sb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_sc {
            get {
                return ResourceManager.GetString("Country_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_sd {
            get {
                return ResourceManager.GetString("Country_sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_se {
            get {
                return ResourceManager.GetString("Country_se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_sg {
            get {
                return ResourceManager.GetString("Country_sg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_sh {
            get {
                return ResourceManager.GetString("Country_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_si {
            get {
                return ResourceManager.GetString("Country_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_sj {
            get {
                return ResourceManager.GetString("Country_sj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_sk {
            get {
                return ResourceManager.GetString("Country_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_sl {
            get {
                return ResourceManager.GetString("Country_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_sm {
            get {
                return ResourceManager.GetString("Country_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_sn {
            get {
                return ResourceManager.GetString("Country_sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_so {
            get {
                return ResourceManager.GetString("Country_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|country.
        /// </summary>
        internal static string Country_sr {
            get {
                return ResourceManager.GetString("Country_sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ss {
            get {
                return ResourceManager.GetString("Country_ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_st {
            get {
                return ResourceManager.GetString("Country_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_sv {
            get {
                return ResourceManager.GetString("Country_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_sx {
            get {
                return ResourceManager.GetString("Country_sx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_sy {
            get {
                return ResourceManager.GetString("Country_sy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_sz {
            get {
                return ResourceManager.GetString("Country_sz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_tc {
            get {
                return ResourceManager.GetString("Country_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_td {
            get {
                return ResourceManager.GetString("Country_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_tg {
            get {
                return ResourceManager.GetString("Country_tg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|zip|country.
        /// </summary>
        internal static string Country_th {
            get {
                return ResourceManager.GetString("Country_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_tj {
            get {
                return ResourceManager.GetString("Country_tj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|zip|country.
        /// </summary>
        internal static string Country_tk {
            get {
                return ResourceManager.GetString("Country_tk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_tl {
            get {
                return ResourceManager.GetString("Country_tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_tm {
            get {
                return ResourceManager.GetString("Country_tm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_tn {
            get {
                return ResourceManager.GetString("Country_tn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_to {
            get {
                return ResourceManager.GetString("Country_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|state|city|country.
        /// </summary>
        internal static string Country_tr {
            get {
                return ResourceManager.GetString("Country_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_tt {
            get {
                return ResourceManager.GetString("Country_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_tv {
            get {
                return ResourceManager.GetString("Country_tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country,zip,state,city,street.
        /// </summary>
        internal static string Country_tw {
            get {
                return ResourceManager.GetString("Country_tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_tz {
            get {
                return ResourceManager.GetString("Country_tz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|region|state|zip|country.
        /// </summary>
        internal static string Country_ua {
            get {
                return ResourceManager.GetString("Country_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ug {
            get {
                return ResourceManager.GetString("Country_ug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_uk {
            get {
                return ResourceManager.GetString("Country_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_um {
            get {
                return ResourceManager.GetString("Country_um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_us {
            get {
                return ResourceManager.GetString("Country_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|state|country.
        /// </summary>
        internal static string Country_uy {
            get {
                return ResourceManager.GetString("Country_uy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|country.
        /// </summary>
        internal static string Country_uz {
            get {
                return ResourceManager.GetString("Country_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_va {
            get {
                return ResourceManager.GetString("Country_va", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_vc {
            get {
                return ResourceManager.GetString("Country_vc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|zip|state|country.
        /// </summary>
        internal static string Country_ve {
            get {
                return ResourceManager.GetString("Country_ve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_vi {
            get {
                return ResourceManager.GetString("Country_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|state|city|zip|country.
        /// </summary>
        internal static string Country_vn {
            get {
                return ResourceManager.GetString("Country_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_vu {
            get {
                return ResourceManager.GetString("Country_vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_wf {
            get {
                return ResourceManager.GetString("Country_wf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_ws {
            get {
                return ResourceManager.GetString("Country_ws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_ye {
            get {
                return ResourceManager.GetString("Country_ye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_yt {
            get {
                return ResourceManager.GetString("Country_yt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|state|zip|country.
        /// </summary>
        internal static string Country_za {
            get {
                return ResourceManager.GetString("Country_za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|zip|city|country.
        /// </summary>
        internal static string Country_zm {
            get {
                return ResourceManager.GetString("Country_zm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street|city|country.
        /// </summary>
        internal static string Country_zw {
            get {
                return ResourceManager.GetString("Country_zw", resourceCulture);
            }
        }
    }
}
